# Generated by Django 3.0.5 on 2020-10-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Samy', max_length=40),
            preserve_default=False,
        ),
    ]
